// Data for seed-markets.ts: every sovereign country, with its capital plus
// two other widely-known major cities, each with an IANA timezone.
export interface MarketCitySeed {
  countryCode: string;
  countryName: string;
  cityName: string;
  timezone: string;
}

export const MARKET_SEED_DATA: MarketCitySeed[] = [
  // ---- Africa ----
  ...city(
    'DZ',
    'Algeria',
    ['Algiers', 'Oran', 'Constantine'],
    'Africa/Algiers',
  ),
  ...city('AO', 'Angola', ['Luanda', 'Huambo', 'Lobito'], 'Africa/Luanda'),
  ...city(
    'BJ',
    'Benin',
    ['Porto-Novo', 'Cotonou', 'Parakou'],
    'Africa/Porto-Novo',
  ),
  ...city(
    'BW',
    'Botswana',
    ['Gaborone', 'Francistown', 'Maun'],
    'Africa/Gaborone',
  ),
  ...city(
    'BF',
    'Burkina Faso',
    ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'],
    'Africa/Ouagadougou',
  ),
  ...city(
    'BI',
    'Burundi',
    ['Gitega', 'Bujumbura', 'Ngozi'],
    'Africa/Bujumbura',
  ),
  ...city('CM', 'Cameroon', ['Yaoundé', 'Douala', 'Garoua'], 'Africa/Douala'),
  ...city(
    'CV',
    'Cabo Verde',
    ['Praia', 'Mindelo', 'Santa Maria'],
    'Atlantic/Cape_Verde',
  ),
  ...city(
    'CF',
    'Central African Republic',
    ['Bangui', 'Bimbo', 'Berbérati'],
    'Africa/Bangui',
  ),
  ...city('TD', 'Chad', ["N'Djamena", 'Moundou', 'Sarh'], 'Africa/Ndjamena'),
  ...city('KM', 'Comoros', ['Moroni', 'Mutsamudu', 'Fomboni'], 'Indian/Comoro'),
  ...city(
    'CG',
    'Congo (Republic of the)',
    ['Brazzaville', 'Pointe-Noire', 'Dolisie'],
    'Africa/Brazzaville',
  ),
  ...city(
    'CD',
    'Congo (DRC)',
    ['Kinshasa', 'Lubumbashi', 'Goma'],
    'Africa/Kinshasa',
  ),
  ...city(
    'DJ',
    'Djibouti',
    ['Djibouti City', 'Ali Sabieh', 'Tadjoura'],
    'Africa/Djibouti',
  ),
  ...city('EG', 'Egypt', ['Cairo', 'Alexandria', 'Giza'], 'Africa/Cairo'),
  ...city(
    'GQ',
    'Equatorial Guinea',
    ['Malabo', 'Bata', 'Ebebiyín'],
    'Africa/Malabo',
  ),
  ...city('ER', 'Eritrea', ['Asmara', 'Keren', 'Massawa'], 'Africa/Asmara'),
  ...city(
    'SZ',
    'Eswatini',
    ['Mbabane', 'Manzini', 'Lobamba'],
    'Africa/Mbabane',
  ),
  ...city(
    'ET',
    'Ethiopia',
    ['Addis Ababa', 'Dire Dawa', 'Mekelle'],
    'Africa/Addis_Ababa',
  ),
  ...city(
    'GA',
    'Gabon',
    ['Libreville', 'Port-Gentil', 'Franceville'],
    'Africa/Libreville',
  ),
  ...city('GM', 'Gambia', ['Banjul', 'Serekunda', 'Brikama'], 'Africa/Banjul'),
  ...city('GH', 'Ghana', ['Accra', 'Kumasi', 'Tamale'], 'Africa/Accra'),
  ...city('GN', 'Guinea', ['Conakry', 'Nzérékoré', 'Kankan'], 'Africa/Conakry'),
  ...city('GW', 'Guinea-Bissau', ['Bissau', 'Bafatá', 'Gabú'], 'Africa/Bissau'),
  ...city(
    'CI',
    "Côte d'Ivoire",
    ['Abidjan', 'Yamoussoukro', 'Bouaké'],
    'Africa/Abidjan',
  ),
  ...city('KE', 'Kenya', ['Nairobi', 'Mombasa', 'Kisumu'], 'Africa/Nairobi'),
  ...city(
    'LS',
    'Lesotho',
    ['Maseru', 'Teyateyaneng', 'Mafeteng'],
    'Africa/Maseru',
  ),
  ...city(
    'LR',
    'Liberia',
    ['Monrovia', 'Gbarnga', 'Buchanan'],
    'Africa/Monrovia',
  ),
  ...city('LY', 'Libya', ['Tripoli', 'Benghazi', 'Misrata'], 'Africa/Tripoli'),
  ...city(
    'MG',
    'Madagascar',
    ['Antananarivo', 'Toamasina', 'Antsirabe'],
    'Indian/Antananarivo',
  ),
  ...city('MW', 'Malawi', ['Lilongwe', 'Blantyre', 'Mzuzu'], 'Africa/Blantyre'),
  ...city('ML', 'Mali', ['Bamako', 'Sikasso', 'Mopti'], 'Africa/Bamako'),
  ...city(
    'MR',
    'Mauritania',
    ['Nouakchott', 'Nouadhibou', 'Kiffa'],
    'Africa/Nouakchott',
  ),
  ...city(
    'MU',
    'Mauritius',
    ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix'],
    'Indian/Mauritius',
  ),
  ...city(
    'MA',
    'Morocco',
    ['Rabat', 'Casablanca', 'Marrakesh'],
    'Africa/Casablanca',
  ),
  ...city('MZ', 'Mozambique', ['Maputo', 'Beira', 'Nampula'], 'Africa/Maputo'),
  ...city(
    'NA',
    'Namibia',
    ['Windhoek', 'Walvis Bay', 'Swakopmund'],
    'Africa/Windhoek',
  ),
  ...city('NE', 'Niger', ['Niamey', 'Zinder', 'Maradi'], 'Africa/Niamey'),
  ...city('NG', 'Nigeria', ['Abuja', 'Lagos', 'Kano'], 'Africa/Lagos'),
  ...city('RW', 'Rwanda', ['Kigali', 'Butare', 'Gisenyi'], 'Africa/Kigali'),
  ...city(
    'ST',
    'São Tomé and Príncipe',
    ['São Tomé', 'Santo António', 'Neves'],
    'Africa/Sao_Tome',
  ),
  ...city('SN', 'Senegal', ['Dakar', 'Touba', 'Thiès'], 'Africa/Dakar'),
  ...city(
    'SC',
    'Seychelles',
    ['Victoria', 'Anse Boileau', 'Beau Vallon'],
    'Indian/Mahe',
  ),
  ...city(
    'SL',
    'Sierra Leone',
    ['Freetown', 'Bo', 'Kenema'],
    'Africa/Freetown',
  ),
  ...city(
    'SO',
    'Somalia',
    ['Mogadishu', 'Hargeisa', 'Kismayo'],
    'Africa/Mogadishu',
  ),
  ...city(
    'ZA',
    'South Africa',
    ['Pretoria', 'Johannesburg', 'Cape Town'],
    'Africa/Johannesburg',
  ),
  ...city('SS', 'South Sudan', ['Juba', 'Wau', 'Malakal'], 'Africa/Juba'),
  ...city(
    'SD',
    'Sudan',
    ['Khartoum', 'Omdurman', 'Port Sudan'],
    'Africa/Khartoum',
  ),
  ...city(
    'TZ',
    'Tanzania',
    ['Dodoma', 'Dar es Salaam', 'Arusha'],
    'Africa/Dar_es_Salaam',
  ),
  ...city('TG', 'Togo', ['Lomé', 'Sokodé', 'Kara'], 'Africa/Lome'),
  ...city('TN', 'Tunisia', ['Tunis', 'Sfax', 'Sousse'], 'Africa/Tunis'),
  ...city('UG', 'Uganda', ['Kampala', 'Gulu', 'Mbarara'], 'Africa/Kampala'),
  ...city('ZM', 'Zambia', ['Lusaka', 'Kitwe', 'Ndola'], 'Africa/Lusaka'),
  ...city('ZW', 'Zimbabwe', ['Harare', 'Bulawayo', 'Mutare'], 'Africa/Harare'),

  // ---- Asia ----
  ...city('AF', 'Afghanistan', ['Kabul', 'Herat', 'Kandahar'], 'Asia/Kabul'),
  ...city('AM', 'Armenia', ['Yerevan', 'Gyumri', 'Vanadzor'], 'Asia/Yerevan'),
  ...city('AZ', 'Azerbaijan', ['Baku', 'Ganja', 'Sumqayit'], 'Asia/Baku'),
  ...city('BH', 'Bahrain', ['Manama', 'Riffa', 'Muharraq'], 'Asia/Bahrain'),
  ...city('BD', 'Bangladesh', ['Dhaka', 'Chittagong', 'Khulna'], 'Asia/Dhaka'),
  ...city(
    'BT',
    'Bhutan',
    ['Thimphu', 'Phuntsholing', 'Punakha'],
    'Asia/Thimphu',
  ),
  ...city(
    'BN',
    'Brunei',
    ['Bandar Seri Begawan', 'Kuala Belait', 'Seria'],
    'Asia/Brunei',
  ),
  ...city(
    'KH',
    'Cambodia',
    ['Phnom Penh', 'Siem Reap', 'Battambang'],
    'Asia/Phnom_Penh',
  ),
  ...city('CN', 'China', ['Beijing', 'Shanghai', 'Guangzhou'], 'Asia/Shanghai'),
  ...city('CY', 'Cyprus', ['Nicosia', 'Limassol', 'Larnaca'], 'Asia/Nicosia'),
  ...city('GE', 'Georgia', ['Tbilisi', 'Batumi', 'Kutaisi'], 'Asia/Tbilisi'),
  ...city('IN', 'India', ['New Delhi', 'Mumbai', 'Bengaluru'], 'Asia/Kolkata'),
  ...city(
    'ID',
    'Indonesia',
    ['Jakarta', 'Surabaya', 'Bandung'],
    'Asia/Jakarta',
  ),
  ...city('IR', 'Iran', ['Tehran', 'Mashhad', 'Isfahan'], 'Asia/Tehran'),
  ...city('IQ', 'Iraq', ['Baghdad', 'Basra', 'Mosul'], 'Asia/Baghdad'),
  ...city('IL', 'Israel', ['Jerusalem', 'Tel Aviv', 'Haifa'], 'Asia/Jerusalem'),
  ...city('JP', 'Japan', ['Tokyo', 'Osaka', 'Yokohama'], 'Asia/Tokyo'),
  ...city('JO', 'Jordan', ['Amman', 'Zarqa', 'Irbid'], 'Asia/Amman'),
  ...city('KZ', 'Kazakhstan', ['Astana', 'Almaty', 'Shymkent'], 'Asia/Almaty'),
  ...city('KW', 'Kuwait', ['Kuwait City', 'Hawalli', 'Salmiya'], 'Asia/Kuwait'),
  ...city('KG', 'Kyrgyzstan', ['Bishkek', 'Osh', 'Jalal-Abad'], 'Asia/Bishkek'),
  ...city(
    'LA',
    'Laos',
    ['Vientiane', 'Luang Prabang', 'Pakse'],
    'Asia/Vientiane',
  ),
  ...city('LB', 'Lebanon', ['Beirut', 'Tripoli', 'Sidon'], 'Asia/Beirut'),
  ...city(
    'MY',
    'Malaysia',
    ['Kuala Lumpur', 'George Town', 'Johor Bahru'],
    'Asia/Kuala_Lumpur',
  ),
  ...city(
    'MV',
    'Maldives',
    ['Malé', 'Addu City', 'Fuvahmulah'],
    'Indian/Maldives',
  ),
  ...city(
    'MN',
    'Mongolia',
    ['Ulaanbaatar', 'Erdenet', 'Darkhan'],
    'Asia/Ulaanbaatar',
  ),
  ...city('MM', 'Myanmar', ['Naypyidaw', 'Yangon', 'Mandalay'], 'Asia/Yangon'),
  ...city(
    'NP',
    'Nepal',
    ['Kathmandu', 'Pokhara', 'Lalitpur'],
    'Asia/Kathmandu',
  ),
  ...city(
    'KP',
    'North Korea',
    ['Pyongyang', 'Hamhung', 'Chongjin'],
    'Asia/Pyongyang',
  ),
  ...city('OM', 'Oman', ['Muscat', 'Salalah', 'Sohar'], 'Asia/Muscat'),
  ...city('PK', 'Pakistan', ['Islamabad', 'Karachi', 'Lahore'], 'Asia/Karachi'),
  ...city('PS', 'Palestine', ['Ramallah', 'Gaza City', 'Hebron'], 'Asia/Gaza'),
  ...city(
    'PH',
    'Philippines',
    ['Manila', 'Quezon City', 'Cebu City'],
    'Asia/Manila',
  ),
  ...city('QA', 'Qatar', ['Doha', 'Al Rayyan', 'Al Wakrah'], 'Asia/Qatar'),
  ...city('SA', 'Saudi Arabia', ['Riyadh', 'Jeddah', 'Mecca'], 'Asia/Riyadh'),
  ...city(
    'SG',
    'Singapore',
    ['Singapore', 'Jurong', 'Woodlands'],
    'Asia/Singapore',
  ),
  ...city('KR', 'South Korea', ['Seoul', 'Busan', 'Incheon'], 'Asia/Seoul'),
  ...city('LK', 'Sri Lanka', ['Colombo', 'Kandy', 'Galle'], 'Asia/Colombo'),
  ...city('SY', 'Syria', ['Damascus', 'Aleppo', 'Homs'], 'Asia/Damascus'),
  ...city('TW', 'Taiwan', ['Taipei', 'Kaohsiung', 'Taichung'], 'Asia/Taipei'),
  ...city(
    'TJ',
    'Tajikistan',
    ['Dushanbe', 'Khujand', 'Kulob'],
    'Asia/Dushanbe',
  ),
  ...city(
    'TH',
    'Thailand',
    ['Bangkok', 'Chiang Mai', 'Phuket'],
    'Asia/Bangkok',
  ),
  ...city('TL', 'Timor-Leste', ['Dili', 'Baucau', 'Maliana'], 'Asia/Dili'),
  ...city('TR', 'Turkey', ['Ankara', 'Istanbul', 'Izmir'], 'Europe/Istanbul'),
  ...city(
    'TM',
    'Turkmenistan',
    ['Ashgabat', 'Türkmenabat', 'Mary'],
    'Asia/Ashgabat',
  ),
  ...city(
    'AE',
    'United Arab Emirates',
    ['Abu Dhabi', 'Dubai', 'Sharjah'],
    'Asia/Dubai',
  ),
  ...city(
    'UZ',
    'Uzbekistan',
    ['Tashkent', 'Samarkand', 'Bukhara'],
    'Asia/Tashkent',
  ),
  ...city(
    'VN',
    'Vietnam',
    ['Hanoi', 'Ho Chi Minh City', 'Da Nang'],
    'Asia/Ho_Chi_Minh',
  ),
  ...city('YE', 'Yemen', ["Sana'a", 'Aden', 'Taiz'], 'Asia/Aden'),

  // ---- Europe ----
  ...city('AL', 'Albania', ['Tirana', 'Durrës', 'Vlorë'], 'Europe/Tirane'),
  ...city(
    'AD',
    'Andorra',
    ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp'],
    'Europe/Andorra',
  ),
  ...city('AT', 'Austria', ['Vienna', 'Graz', 'Linz'], 'Europe/Vienna'),
  ...city('BY', 'Belarus', ['Minsk', 'Gomel', 'Vitebsk'], 'Europe/Minsk'),
  ...city('BE', 'Belgium', ['Brussels', 'Antwerp', 'Ghent'], 'Europe/Brussels'),
  ...city(
    'BA',
    'Bosnia and Herzegovina',
    ['Sarajevo', 'Banja Luka', 'Mostar'],
    'Europe/Sarajevo',
  ),
  ...city('BG', 'Bulgaria', ['Sofia', 'Plovdiv', 'Varna'], 'Europe/Sofia'),
  ...city('HR', 'Croatia', ['Zagreb', 'Split', 'Rijeka'], 'Europe/Zagreb'),
  ...city(
    'CZ',
    'Czech Republic',
    ['Prague', 'Brno', 'Ostrava'],
    'Europe/Prague',
  ),
  ...city(
    'DK',
    'Denmark',
    ['Copenhagen', 'Aarhus', 'Odense'],
    'Europe/Copenhagen',
  ),
  ...city('EE', 'Estonia', ['Tallinn', 'Tartu', 'Narva'], 'Europe/Tallinn'),
  ...city('FI', 'Finland', ['Helsinki', 'Espoo', 'Tampere'], 'Europe/Helsinki'),
  ...city('FR', 'France', ['Paris', 'Marseille', 'Lyon'], 'Europe/Paris'),
  ...city('DE', 'Germany', ['Berlin', 'Munich', 'Hamburg'], 'Europe/Berlin'),
  ...city(
    'GR',
    'Greece',
    ['Athens', 'Thessaloniki', 'Patras'],
    'Europe/Athens',
  ),
  ...city(
    'HU',
    'Hungary',
    ['Budapest', 'Debrecen', 'Szeged'],
    'Europe/Budapest',
  ),
  ...city(
    'IS',
    'Iceland',
    ['Reykjavík', 'Kópavogur', 'Akureyri'],
    'Atlantic/Reykjavik',
  ),
  ...city('IE', 'Ireland', ['Dublin', 'Cork', 'Galway'], 'Europe/Dublin'),
  ...city('IT', 'Italy', ['Rome', 'Milan', 'Naples'], 'Europe/Rome'),
  ...city('XK', 'Kosovo', ['Pristina', 'Prizren', 'Peja'], 'Europe/Belgrade'),
  ...city('LV', 'Latvia', ['Riga', 'Daugavpils', 'Liepāja'], 'Europe/Riga'),
  ...city(
    'LI',
    'Liechtenstein',
    ['Vaduz', 'Schaan', 'Balzers'],
    'Europe/Vaduz',
  ),
  ...city(
    'LT',
    'Lithuania',
    ['Vilnius', 'Kaunas', 'Klaipėda'],
    'Europe/Vilnius',
  ),
  ...city(
    'LU',
    'Luxembourg',
    ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange'],
    'Europe/Luxembourg',
  ),
  ...city('MT', 'Malta', ['Valletta', 'Birkirkara', 'Mosta'], 'Europe/Malta'),
  ...city(
    'MD',
    'Moldova',
    ['Chișinău', 'Tiraspol', 'Bălți'],
    'Europe/Chisinau',
  ),
  ...city(
    'MC',
    'Monaco',
    ['Monaco', 'Monte Carlo', 'La Condamine'],
    'Europe/Monaco',
  ),
  ...city(
    'ME',
    'Montenegro',
    ['Podgorica', 'Nikšić', 'Budva'],
    'Europe/Podgorica',
  ),
  ...city(
    'NL',
    'Netherlands',
    ['Amsterdam', 'Rotterdam', 'The Hague'],
    'Europe/Amsterdam',
  ),
  ...city(
    'MK',
    'North Macedonia',
    ['Skopje', 'Bitola', 'Kumanovo'],
    'Europe/Skopje',
  ),
  ...city('NO', 'Norway', ['Oslo', 'Bergen', 'Trondheim'], 'Europe/Oslo'),
  ...city('PL', 'Poland', ['Warsaw', 'Kraków', 'Łódź'], 'Europe/Warsaw'),
  ...city('PT', 'Portugal', ['Lisbon', 'Porto', 'Braga'], 'Europe/Lisbon'),
  ...city(
    'RO',
    'Romania',
    ['Bucharest', 'Cluj-Napoca', 'Timișoara'],
    'Europe/Bucharest',
  ),
  ...city(
    'RU',
    'Russia',
    ['Moscow', 'Saint Petersburg', 'Novosibirsk'],
    'Europe/Moscow',
  ),
  ...city(
    'SM',
    'San Marino',
    ['San Marino', 'Serravalle', 'Borgo Maggiore'],
    'Europe/San_Marino',
  ),
  ...city('RS', 'Serbia', ['Belgrade', 'Novi Sad', 'Niš'], 'Europe/Belgrade'),
  ...city(
    'SK',
    'Slovakia',
    ['Bratislava', 'Košice', 'Prešov'],
    'Europe/Bratislava',
  ),
  ...city(
    'SI',
    'Slovenia',
    ['Ljubljana', 'Maribor', 'Celje'],
    'Europe/Ljubljana',
  ),
  ...city('ES', 'Spain', ['Madrid', 'Barcelona', 'Valencia'], 'Europe/Madrid'),
  ...city(
    'SE',
    'Sweden',
    ['Stockholm', 'Gothenburg', 'Malmö'],
    'Europe/Stockholm',
  ),
  ...city('CH', 'Switzerland', ['Bern', 'Zurich', 'Geneva'], 'Europe/Zurich'),
  ...city('UA', 'Ukraine', ['Kyiv', 'Kharkiv', 'Odesa'], 'Europe/Kyiv'),
  ...city(
    'GB',
    'United Kingdom',
    ['London', 'Manchester', 'Birmingham'],
    'Europe/London',
  ),
  ...city(
    'VA',
    'Vatican City',
    ['Vatican City', 'Vatican City', 'Vatican City'],
    'Europe/Vatican',
  ),

  // ---- North America ----
  ...city(
    'AG',
    'Antigua and Barbuda',
    ["St. John's", 'All Saints', 'Liberta'],
    'America/Antigua',
  ),
  ...city(
    'BS',
    'Bahamas',
    ['Nassau', 'Freeport', 'West End'],
    'America/Nassau',
  ),
  ...city(
    'BB',
    'Barbados',
    ['Bridgetown', 'Speightstown', 'Oistins'],
    'America/Barbados',
  ),
  ...city(
    'BZ',
    'Belize',
    ['Belmopan', 'Belize City', 'San Ignacio'],
    'America/Belize',
  ),
  ...city(
    'CA',
    'Canada',
    ['Ottawa', 'Toronto', 'Vancouver'],
    'America/Toronto',
  ),
  ...city(
    'CR',
    'Costa Rica',
    ['San José', 'Alajuela', 'Cartago'],
    'America/Costa_Rica',
  ),
  ...city(
    'CU',
    'Cuba',
    ['Havana', 'Santiago de Cuba', 'Camagüey'],
    'America/Havana',
  ),
  ...city(
    'DM',
    'Dominica',
    ['Roseau', 'Portsmouth', 'Marigot'],
    'America/Dominica',
  ),
  ...city(
    'DO',
    'Dominican Republic',
    ['Santo Domingo', 'Santiago de los Caballeros', 'Puerto Plata'],
    'America/Santo_Domingo',
  ),
  ...city(
    'SV',
    'El Salvador',
    ['San Salvador', 'Santa Ana', 'San Miguel'],
    'America/El_Salvador',
  ),
  ...city(
    'GD',
    'Grenada',
    ["St. George's", 'Gouyave', 'Grenville'],
    'America/Grenada',
  ),
  ...city(
    'GT',
    'Guatemala',
    ['Guatemala City', 'Mixco', 'Quetzaltenango'],
    'America/Guatemala',
  ),
  ...city(
    'HT',
    'Haiti',
    ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves'],
    'America/Port-au-Prince',
  ),
  ...city(
    'HN',
    'Honduras',
    ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba'],
    'America/Tegucigalpa',
  ),
  ...city(
    'JM',
    'Jamaica',
    ['Kingston', 'Montego Bay', 'Spanish Town'],
    'America/Jamaica',
  ),
  ...city(
    'MX',
    'Mexico',
    ['Mexico City', 'Guadalajara', 'Monterrey'],
    'America/Mexico_City',
  ),
  ...city('NI', 'Nicaragua', ['Managua', 'León', 'Granada'], 'America/Managua'),
  ...city(
    'PA',
    'Panama',
    ['Panama City', 'San Miguelito', 'Colón'],
    'America/Panama',
  ),
  ...city(
    'KN',
    'Saint Kitts and Nevis',
    ['Basseterre', 'Charlestown', 'Sandy Point Town'],
    'America/St_Kitts',
  ),
  ...city(
    'LC',
    'Saint Lucia',
    ['Castries', 'Vieux Fort', 'Soufrière'],
    'America/St_Lucia',
  ),
  ...city(
    'VC',
    'Saint Vincent and the Grenadines',
    ['Kingstown', 'Georgetown', 'Barrouallie'],
    'America/St_Vincent',
  ),
  ...city(
    'TT',
    'Trinidad and Tobago',
    ['Port of Spain', 'San Fernando', 'Chaguanas'],
    'America/Port_of_Spain',
  ),
  ...city(
    'US',
    'United States',
    ['Washington, D.C.', 'New York City', 'Los Angeles'],
    'America/New_York',
  ),

  // ---- South America ----
  ...city(
    'AR',
    'Argentina',
    ['Buenos Aires', 'Córdoba', 'Rosario'],
    'America/Argentina/Buenos_Aires',
  ),
  ...city(
    'BO',
    'Bolivia',
    ['Sucre', 'La Paz', 'Santa Cruz de la Sierra'],
    'America/La_Paz',
  ),
  ...city(
    'BR',
    'Brazil',
    ['Brasília', 'São Paulo', 'Rio de Janeiro'],
    'America/Sao_Paulo',
  ),
  ...city(
    'CL',
    'Chile',
    ['Santiago', 'Valparaíso', 'Concepción'],
    'America/Santiago',
  ),
  ...city('CO', 'Colombia', ['Bogotá', 'Medellín', 'Cali'], 'America/Bogota'),
  ...city(
    'EC',
    'Ecuador',
    ['Quito', 'Guayaquil', 'Cuenca'],
    'America/Guayaquil',
  ),
  ...city(
    'GY',
    'Guyana',
    ['Georgetown', 'Linden', 'New Amsterdam'],
    'America/Guyana',
  ),
  ...city(
    'PY',
    'Paraguay',
    ['Asunción', 'Ciudad del Este', 'Luque'],
    'America/Asuncion',
  ),
  ...city('PE', 'Peru', ['Lima', 'Arequipa', 'Trujillo'], 'America/Lima'),
  ...city(
    'SR',
    'Suriname',
    ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'],
    'America/Paramaribo',
  ),
  ...city(
    'UY',
    'Uruguay',
    ['Montevideo', 'Salto', 'Ciudad de la Costa'],
    'America/Montevideo',
  ),
  ...city(
    'VE',
    'Venezuela',
    ['Caracas', 'Maracaibo', 'Valencia'],
    'America/Caracas',
  ),

  // ---- Oceania ----
  ...city(
    'AU',
    'Australia',
    ['Canberra', 'Sydney', 'Melbourne'],
    'Australia/Sydney',
  ),
  ...city('FJ', 'Fiji', ['Suva', 'Nadi', 'Lautoka'], 'Pacific/Fiji'),
  ...city(
    'KI',
    'Kiribati',
    ['South Tarawa', 'Betio', 'Bikenibeu'],
    'Pacific/Tarawa',
  ),
  ...city(
    'MH',
    'Marshall Islands',
    ['Majuro', 'Ebeye', 'Jaluit'],
    'Pacific/Majuro',
  ),
  ...city('FM', 'Micronesia', ['Palikir', 'Weno', 'Kolonia'], 'Pacific/Chuuk'),
  ...city('NR', 'Nauru', ['Yaren', 'Denigomodu', 'Meneng'], 'Pacific/Nauru'),
  ...city(
    'NZ',
    'New Zealand',
    ['Wellington', 'Auckland', 'Christchurch'],
    'Pacific/Auckland',
  ),
  ...city('PW', 'Palau', ['Ngerulmud', 'Koror', 'Airai'], 'Pacific/Palau'),
  ...city(
    'PG',
    'Papua New Guinea',
    ['Port Moresby', 'Lae', 'Mount Hagen'],
    'Pacific/Port_Moresby',
  ),
  ...city('WS', 'Samoa', ['Apia', 'Vaitele', 'Faleula'], 'Pacific/Apia'),
  ...city(
    'SB',
    'Solomon Islands',
    ['Honiara', 'Auki', 'Gizo'],
    'Pacific/Guadalcanal',
  ),
  ...city(
    'TO',
    'Tonga',
    ["Nuku'alofa", 'Neiafu', 'Pangai'],
    'Pacific/Tongatapu',
  ),
  ...city(
    'TV',
    'Tuvalu',
    ['Funafuti', 'Savave', 'Tanrake'],
    'Pacific/Funafuti',
  ),
  ...city(
    'VU',
    'Vanuatu',
    ['Port Vila', 'Luganville', 'Norsup'],
    'Pacific/Efate',
  ),
];

function city(
  countryCode: string,
  countryName: string,
  cities: string[],
  timezone: string,
): MarketCitySeed[] {
  const seen = new Set<string>();
  return cities
    .filter((cityName) => {
      if (seen.has(cityName)) return false;
      seen.add(cityName);
      return true;
    })
    .map((cityName) => ({ countryCode, countryName, cityName, timezone }));
}
