server {
    listen 80;
    listen [::]:80;
    server_name 135.181.146.130;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 404;
    }
}

