import { mkdtemp, readFile, writeFile, access } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Readable } from 'node:stream';
import { LocalDiskVideoStorage } from './video-storage.service';

function storageIn(root: string) {
  const config = {
    get: (key: string) => (key === 'VIDEO_STORAGE_ROOT' ? root : undefined),
  };
  return new LocalDiskVideoStorage(config as never);
}

describe('LocalDiskVideoStorage', () => {
  let root: string;
  let storage: LocalDiskVideoStorage;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), 'drift-video-store-'));
    storage = storageIn(root);
  });

  it('round-trips a file', async () => {
    const key = await storage.save(Readable.from('video bytes'), 'clip.mp4');
    const path = storage.localPath(key)!;
    expect(await readFile(path, 'utf8')).toBe('video bytes');
  });

  it('keeps the extension but never the uploaded filename', async () => {
    // The filename comes from a client. Reusing it is how a caller ends up writing
    // wherever the client asked, and how two users overwrite each other's uploads.
    const key = await storage.save(Readable.from('x'), 'my holiday clip.MP4');
    expect(key).toMatch(/\.mp4$/);
    expect(key).not.toContain('holiday');
  });

  it('defaults the extension when the filename has none', async () => {
    const key = await storage.save(Readable.from('x'), 'no-extension');
    expect(key).toMatch(/\.mp4$/);
  });

  it('gives every upload its own key', async () => {
    const a = await storage.save(Readable.from('a'), 'clip.mp4');
    const b = await storage.save(Readable.from('b'), 'clip.mp4');
    expect(a).not.toBe(b);
    expect(await readFile(storage.localPath(a)!, 'utf8')).toBe('a');
    expect(await readFile(storage.localPath(b)!, 'utf8')).toBe('b');
  });

  it('reads a saved file back as a stream', async () => {
    const key = await storage.save(Readable.from('streamed'), 'clip.mp4');
    const chunks: Buffer[] = [];
    for await (const chunk of await storage.read(key))
      chunks.push(chunk as Buffer);
    expect(Buffer.concat(chunks).toString()).toBe('streamed');
  });

  it('deletes a file', async () => {
    const key = await storage.save(Readable.from('bye'), 'clip.mp4');
    await storage.delete(key);
    await expect(access(storage.localPath(key)!)).rejects.toBeTruthy();
  });

  it('treats deleting a missing file as success', async () => {
    // A rejected upload may be deleted twice, or after a failed write. The caller
    // wants the end state, not a race report.
    await expect(
      storage.delete('ab/does-not-exist.mp4'),
    ).resolves.toBeUndefined();
  });

  describe('keys that escape the root', () => {
    // Keys are generated by save(), so these cannot occur in normal operation. They
    // are read back from a database column, which is reason enough to check: a bad
    // row must not become an arbitrary file read or delete.
    it.each(['../../etc/passwd', 'ab/../../../secret.mp4'])(
      'refuses %s',
      async (key) => {
        expect(() => storage.localPath(key)).toThrow(/escapes the root/);
        await expect(storage.delete(key)).rejects.toThrow(/escapes the root/);
      },
    );

    it('does not delete the file a traversal points at', async () => {
      const victim = join(root, '..', 'victim.txt');
      await writeFile(victim, 'still here');

      await expect(storage.delete('../victim.txt')).rejects.toThrow();
      expect(await readFile(victim, 'utf8')).toBe('still here');
    });
  });
});
