import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, rm, stat } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { pipeline } from 'node:stream/promises';
import { randomUUID } from 'node:crypto';
import type { Readable } from 'node:stream';

/**
 * Where uploaded videos live.
 *
 * Every other binary in this codebase is a `Bytes` column in Postgres — profile
 * photos, club media, ticket attachments — and that pattern deliberately stops here.
 * Those are capped at 5MB. A minute of 1080p phone video is comfortably over 100MB,
 * and putting that in Postgres bloats the WAL, every backup and every replica for
 * data the database never queries.
 *
 * The driver sits behind this interface because the hosting decision is genuinely
 * open: the shared box has ~900MiB free and no GPU, so production video will live
 * somewhere else, and that somewhere has cost implications nobody has priced yet.
 * Local disk lets the rest of Phase 1 be built and tested now; an S3-compatible
 * driver slots in underneath without the callers or the `storageKey` column changing.
 *
 * Keys are opaque on purpose. Callers store what `save` returns and hand it back —
 * they never build a path, because a path is exactly the thing that stops being a
 * path when this moves to a bucket.
 */
export interface VideoStorage {
  save(stream: Readable, originalFilename: string): Promise<string>;
  read(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  /**
   * A local filesystem path for `key`, or null when the driver has none.
   *
   * Exists because the CV service currently reads clips from disk. It is the one
   * place the abstraction leaks, and it returns null rather than throwing so a
   * caller can fall back to streaming the bytes instead of special-casing drivers.
   */
  localPath(key: string): string | null;
}

export const VIDEO_STORAGE = Symbol('VIDEO_STORAGE');

@Injectable()
export class LocalDiskVideoStorage implements VideoStorage {
  private readonly root: string;

  constructor(config: ConfigService) {
    this.root = resolve(
      config.get<string>('VIDEO_STORAGE_ROOT') ??
        join(process.cwd(), 'var', 'videos'),
    );
  }

  /**
   * Writes the stream under a generated key and returns it.
   *
   * The key is a UUID plus the original extension, never the uploaded filename:
   * a filename arrives from a client and can contain `..`, a leading slash, or a
   * Windows drive letter, all of which turn a join into a write somewhere else.
   * The two-character prefix keeps one directory from growing to tens of thousands
   * of entries, which some filesystems handle poorly.
   */
  async save(stream: Readable, originalFilename: string): Promise<string> {
    const extension = this.safeExtension(originalFilename);
    const id = randomUUID();
    const key = `${id.slice(0, 2)}/${id}${extension}`;
    const target = this.pathFor(key);

    await mkdir(dirname(target), { recursive: true });
    await pipeline(stream, createWriteStream(target));
    return key;
  }

  async read(key: string): Promise<Readable> {
    return createReadStream(this.pathFor(key));
  }

  async delete(key: string): Promise<void> {
    // force: a delete that races another delete, or follows a failed write, should
    // leave the caller with the outcome it asked for rather than an ENOENT.
    await rm(this.pathFor(key), { force: true });
  }

  localPath(key: string): string | null {
    return this.pathFor(key);
  }

  async sizeOf(key: string): Promise<number> {
    return (await stat(this.pathFor(key))).size;
  }

  /**
   * Resolves a key under the storage root, refusing anything that escapes it.
   *
   * Keys are generated by `save`, so in normal operation this cannot trigger. It is
   * here because the column holding them is read back from the database, and a
   * traversal that reached this method would otherwise read or delete arbitrary
   * files. Cheap to check, and the check is the only thing between a bad row and
   * the filesystem.
   */
  private pathFor(key: string): string {
    const target = resolve(this.root, key);
    if (target !== this.root && !target.startsWith(this.root + sep)) {
      throw new Error(`Refusing a storage key that escapes the root: ${key}`);
    }
    return target;
  }

  private safeExtension(filename: string): string {
    const match = /\.([A-Za-z0-9]{1,8})$/.exec(filename ?? '');
    return match ? `.${match[1].toLowerCase()}` : '.mp4';
  }
}
